// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKVmtjvudVblT_TNFSawxL3n-X23dgeZI',
    appId: '1:139329838043:web:490b215c214761028fa5fe',
    messagingSenderId: '139329838043',
    projectId: 'medication-hero',
    authDomain: 'medication-hero.firebaseapp.com',
    storageBucket: 'medication-hero.appspot.com',
    measurementId: 'G-DTCYEPZHR6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhv1lGc6jGjh6AJj3lQSFaCmp8wVDO56w',
    appId: '1:139329838043:android:147c1f01989af9988fa5fe',
    messagingSenderId: '139329838043',
    projectId: 'medication-hero',
    storageBucket: 'medication-hero.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXWTBUi0zEuYAxILjRkn5lJxqI3zQbifQ',
    appId: '1:139329838043:ios:51afe43b0b1c53df8fa5fe',
    messagingSenderId: '139329838043',
    projectId: 'medication-hero',
    storageBucket: 'medication-hero.appspot.com',
    iosBundleId: 'com.medicationhero.medicationhero',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXWTBUi0zEuYAxILjRkn5lJxqI3zQbifQ',
    appId: '1:139329838043:ios:51afe43b0b1c53df8fa5fe',
    messagingSenderId: '139329838043',
    projectId: 'medication-hero',
    storageBucket: 'medication-hero.appspot.com',
    iosBundleId:
        'com.medicationhero.medicationhero', //check if this double name is a problem
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAKVmtjvudVblT_TNFSawxL3n-X23dgeZI',
    appId: '1:139329838043:web:34ed947960a4da128fa5fe',
    messagingSenderId: '139329838043',
    projectId: 'medication-hero',
    authDomain: 'medication-hero.firebaseapp.com',
    storageBucket: 'medication-hero.appspot.com',
    measurementId: 'G-3P4H0TEF0N',
  );
}
